### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by ZnS77** [drudilorenzo/track-openai-cost#5]
Hey I am installing with pip, and it fails with error below:
<img width="976" alt="截屏2024-04-15 22 08 56" src="https://github.com/drudilorenzo/openai-cost-logger/assets/48546978/fc72d62f-1f86-4494-a557-fc6c06a3a93c">
do you have clue what's wrong? 
I am running on macos14.0 with intel cpu. The python environment is 3.10.14.

**Comment by drudilorenzo** [comment]
Thanks a lot for opening the issue!

Just did a quick fix (I'll think of a better solution tmr :))
Now It should work.
